---
language: python
python: "2.7"

sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible & ansible-lint
  - pip install ansible
  - pip install ansible-lint
    
  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook launchpad_lab.yml --syntax-check
  - ansible-lint launchpad_lab.yml
  - ansible-lint launchpadexamplehttpd/launchpad_looper.yml