---
language: python
python: "2.7"

sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible & ansible-lint
  - pip install ansible
  - pip install ansible-lint
  # Install mdl
  - gem install mdl
    
  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook launchpad_lab.yml --syntax-check
  - ansible-lint -x "301" launchpad_lab.yml
  - ansible-lint -x "204" launchpadexamplehttpd/launchpad_looper.yml
  # mdlrc
  - mdl -c .mdlrc .